repos:
  # Core formatting and linting - runs locally before commit
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: ["--fix"]  # Auto-fix what's possible
      - id: ruff-format  # Replaces black for formatting

  # Basic file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-yaml
        exclude: ^recipe/  # Exclude conda recipe (uses Jinja2 templating)
      - id: check-toml
      - id: check-json

  # Optional: Enable these for stricter local development
  # Uncomment if you want type checking locally
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.6.0
  #   hooks:
  #     - id: mypy
  #       args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]
  #       additional_dependencies: [types-requests, types-PyYAML]
  # - repo: https://github.com/psf/black
  #   rev: 23.9.1
  #   hooks:
  #     - id: black
  #       stages: [manual]   # won't run in CI unless invoked explicitly
  # - repo: https://github.com/timothycrosley/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  # - repo: https://github.com/PyCQA/flake8
  #   rev: 6.1.0
  #   hooks:
  #     - id: flake8
