name: Feature Request
description: Suggest an idea for wf2wf
labels: enhancement
body:
  - type: textarea
    id: proposal
    attributes:
      label: Describe the feature
      description: What problem will this feature solve?
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use cases
      description: Specific workflows or scenarios that benefit.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've considered.
