name: Docs

on:
  push:
    branches: [main]
  pull_request:
    paths: ["docs/**", "README.md", "pyproject.toml"]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install docs deps
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]
      - name: Build HTML
        run: |
          sphinx-build -M html docs docs/_build -W --keep-going
      - name: Deploy to Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
